update to palace 0.14

diff --git a/scripts/palace b/scripts/palace
--- a/scripts/palace
+++ b/scripts/palace
@@ -12,7 +12,7 @@ Wrapper for launching Palace using MPI
 Options:
   -h, --help                       Show this help message and exit
   -dry-run, --dry-run              Parse configuration file for errors and exit
-  -serial, --serial                Call Palace without MPI launcher
+  -serial, --serial                Call Palace without MPI launcher, default is false
   -np, --np NUM_PROCS              How many MPI processes to use, default is 1
   -nt, --nt NUM_THREADS            Number of OpenMP threads to use for OpenMP builds, default is 1 or the value of OMP_NUM_THREADS in the environment
   -launcher, --launcher LAUNCHER   MPI launcher, default is \`mpirun\`
@@ -86,7 +86,7 @@ fi
 
 # Try to find the Palace executable
 PALACE_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
-PALACE=$(find $PALACE_DIR -type f -name "palace-*.bin" 2> /dev/null)
+PALACE=$(find $PALACE_DIR -type f -name "palace-*.bin" -o -type l -name "palace-*.bin*" 2> /dev/null)
 if [[ -z "$PALACE" ]]; then
     echo "Error: Could not locate Palace executable in \"$PALACE_DIR\""
     exit 1
@@ -127,11 +127,12 @@ if $SERIAL; then
     # Run sequential simulation
     if [[ -n "$WORK_DIR" ]]; then
         echo ">> cd $WORK_DIR && $PALACE $CONFIG"
-        cd $WORK_DIR && $PALACE $CONFIG
+        cd $WORK_DIR
     else
         echo ">> $PALACE $CONFIG"
-        $PALACE $CONFIG
     fi
+    $PALACE $CONFIG
+    EXIT_CODE=$?
 else
     # Configure parallel MPI execution
     LAUNCHER=${LAUNCHER:-mpirun}
@@ -145,36 +146,40 @@ else
     fi
 
     # Run parallel simulation
+    NODE_FILE=mpi_nodes
     if [[ -n "$PBS_NODEFILE" ]]; then
         # PBS/Torque job
-        NODE_LIST=$PBS_NODEFILE
-        SUBMIT_DIR=$PBS_O_WORKDIR
+        cat $PBS_NODEFILE | sort | uniq > $NODE_FILE
+        WORK_DIR=$PBS_O_WORKDIR
     elif [[ -n "$SLURM_JOB_NODELIST" ]]; then
         # Slurm job
-        NODE_LIST=$SLURM_JOB_NODELIST
-        SUBMIT_DIR=$SLURM_SUBMIT_DIR
+        scontrol show hostnames $SLURM_JOB_NODELIST > $NODE_FILE
+        WORK_DIR=$SLURM_SUBMIT_DIR
     else
-        NODE_LIST=""
-        WORKDIR=""
+        WORK_DIR=""
     fi
-    if [[ -z "$NODE_LIST" ]]; then
+    if [[ -z "$WORK_DIR" ]]; then
         # Local execution
         echo ">> $MPIRUN $PALACE $CONFIG"
         $MPIRUN $PALACE $CONFIG
+        EXIT_CODE=$?
     else
-        NODE_FILE=mpi_nodes
-        cat $NODE_LIST | sort | uniq > $NODE_FILE
         echo The master node of this job is `hostname`
-        echo The working directory is `echo $SUBMIT_DIR`
+        echo The working directory is `echo $WORK_DIR`
         echo This job runs on the following nodes: && cat $NODE_FILE
         MPIRUN="$MPIRUN --hostfile $NODE_FILE"
 
         # Distributed execution
         echo ">> $MPIRUN $PALACE $CONFIG"
         $MPIRUN $PALACE $CONFIG
+        EXIT_CODE=$?
+
         rm $NODE_FILE
     fi
 fi
 
 # Reset user environment
 OMP_NUM_THREADS=$NUM_THREADS_BACKUP
+
+# Return the exit code from Palace
+exit $EXIT_CODE
